// <auto-generated />
using System;
using ColorsApi.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ColorsApi.Migrations
{
    [DbContext(typeof(ColorsDbContext))]
    [Migration("20250404073332_AddSoftDeleteToColorPalette")]
    partial class AddSoftDeleteToColorPalette
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColorsApi.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Blue")
                        .HasColumnType("integer");

                    b.Property<int>("ColorPaletteId")
                        .HasColumnType("integer");

                    b.Property<int>("Green")
                        .HasColumnType("integer");

                    b.Property<int>("Red")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorPaletteId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("ColorsApi.Entities.ColorPalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ColorPalettes");
                });

            modelBuilder.Entity("ColorsApi.Entities.Color", b =>
                {
                    b.HasOne("ColorsApi.Entities.ColorPalette", "ColorPalette")
                        .WithMany("Colors")
                        .HasForeignKey("ColorPaletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorPalette");
                });

            modelBuilder.Entity("ColorsApi.Entities.ColorPalette", b =>
                {
                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
